server:
  port: 8085
  address: localhost

fe:
  port: 4200
  address: localhost

ocr:
  port: 8086
  address: localhost

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: "gmailHere@gmail.com"
    password: "passwordHere"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 6000
          timeout: 2500
          writetimeout: 6000
  jta:
    atomikos:
      properties:
        recovery:
          forget-orphaned-log-entries-delay:
  data:
    mongodb:
      #      username: root
      #      password: example
      #      uri: mongodb://localhost:28555/db
      host: localhost
      port: 8087

#  datasource:
#    url: localhost
#    username: root
#    password: root
#    platform: mongodb
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
jwt:
  secret: RandomBananaPassword

logging:
  level:
    org.springframework.web: debug
    org.hibernate: ERROR