server:
  port: 8085
  address: 127.0.0.1

fe:
  port: 4200
  address: 127.0.0.1

ocr:
  port: 8080
  address: 127.0.0.1

jwt:
  secret: RandomBananaPassword

logging:
  level:
    org.springframework.web: debug
    org.hibernate: ERROR

#spring:
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: "gmailHere@gmail.com"
#    password: "passwordHere"
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#          connectiontimeout: 6000
#          timeout: 2500
#          writetimeout: 6000

---

spring:
  profiles: default
  mail:
    host: smtp.gmail.com
    port: 587
    username: "gmailHere@gmail.com"
    password: "passwordHere"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 6000
          timeout: 2500
          writetimeout: 6000
#spring:
#  profiles: normal
  data:
    mongodb:
      #      username: root
      #      password: example
      #      uri: mongodb://localhost:28555/db
      host: 127.0.0.1
      port: 8087

---

spring:
  profiles: test
  mail:
    host: smtp.gmail.com
    port: 587
    username: "gmailHere@gmail.com"
    password: "passwordHere"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 6000
          timeout: 2500
          writetimeout: 6000
#  data:
#    mongodb:
#      #      username: root
#      #      password: example
#      #      uri: mongodb://localhost:28555/db
#      host: 127.0.0.1
#      port: 27017