server:
  port: 8085
  address: 127.0.0.1
  servlet:
    context-path: /api

fe:
  port: 4200
  address: 127.0.0.1

ocr:
  port: 8086
  address: 127.0.0.1

jwt:
  secret: RandomBananaPassword

logging:
  level:
    org.springframework.web: debug
    org.hibernate: ERROR

# Swagger springdoc
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /v3/swagger-ui.html
    operations-sorter: method

#spring:
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: "gmailHere@gmail.com"
#    password: "passwordHere"
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#          connectiontimeout: 6000
#          timeout: 2500
#          writetimeout: 6000

---

spring:
  profiles: default
  mail:
    host: smtp.gmail.com
    port: 587
    username: "gmailHere@gmail.com"
    password: "passwordHere"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 6000
          timeout: 2500
          writetimeout: 6000
#spring:
#  profiles: normal
  data:
    mongodb:
      #      username: root
      #      password: example
      #      uri: mongodb://localhost:28555/db
      host: 127.0.0.1
      port: 27017

---

spring:
  profiles: test
  mail:
    host: smtp.gmail.com
    port: 587
    username: "gmailHere@gmail.com"
    password: "passwordHere"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 6000
          timeout: 2500
          writetimeout: 6000
#  data:
#    mongodb:
#      #      username: root
#      #      password: example
#      #      uri: mongodb://localhost:28555/db
#      host: 127.0.0.1
#      port: 27017
