version: "3.8"

services:
  mongo-db:
    container_name: mongo-db
    image: mongo:4.4.1
    ports:
      - "27017:27017"
  #    volumes:
  #      - mongodbdata:/data/db
  ocr-api:
    container_name: ocr-api
    image: madgyver/docs-archive-ocr-api:latest
    command:
      --tesseract.path=/usr/share/tessdata/
      --server.address=0.0.0.0
    ports:
      - "8086:8086"

  backend-api:
    container_name: backend-api
    image: madgyver/docs-archive-backend-api:latest
    command:
      --server.address=0.0.0.0
      --spring.data.mongodb.host=mongo-db
      --ocr.address=ocr-api
      --fe.port=80
      --spring.mail.username=testMailTobeFilled@gmail.com
      --spring.mail.password=PasswordForMail
    ports:
      - "8085:8085"

  frontend:
    container_name: frontend
    image: madgyver/docs-archive-frontend:latest
    ports:
      - "80:80"


#  web:
#    ports:
#      - "5000:5000"
#    volumes:
#      - .:/code
#      - logvolume01:/var/log
#    links:
#      - redis
#  redis:
#    image: redis
#volumes:
#  mongodbdata:
#networks:
#  backend-com:

