version: "3.8"

services:
  mongo-db:
    container_name: mongo-db
    image: mongo:4.4.1
    network_mode: "host"
    ports:
      - "27127:27127"
    volumes:
      - mongodbdata:/data/db
  ocr-api:
    container_name: ocr-api
    image: madgyver/docs-archive-ocr-api:latest
    command: --tesseract.path=/usr/share/tessdata/
    network_mode: "host"
    ports:
      - "8086:8086"

  backend-api:
    container_name: backend-api
    image: madgyver/docs-archive-backend-api:latest
    command:
#      --spring.data.mongodb.host=mongo-db
#      --ocr.address=ocr-api
      --spring.data.mongodb.host=localhost
      --ocr.address=localhost
    network_mode: "host"
    ports:
      - "8085:8085"

  frontend:
    container_name: frontend
    image: madgyver/docs-archive-frontend:latest
    network_mode: "host"
    ports:
      - "4200:80"

#    links:

#  web:
#    ports:
#      - "5000:5000"
#    volumes:
#      - .:/code
#      - logvolume01:/var/log
#    links:
#      - redis
#  redis:
#    image: redis
volumes:
  mongodbdata:
#networks:

